auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new", views.create, name="new"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("addToList/<int:id>", views.addToList, name="addToList"),
    path("removeFromList/<int:id>", views.removeFromList, name="removeFromList"),
    path("placeBid/<int:id>", views.placeBid, name="placeBid"),
    path("close/<int:id>", views.close, name="close"),
    path("comment/<int:id>", views.comment, name="comment"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("<str:username>/listings", views.myListings, name="myListings")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

    def __str__(self):
        return f"{self.username}"

class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=256)
    basePrice = models.PositiveIntegerField()
    imageURL = models.URLField(blank=True)
    category = models.CharField(max_length=11, choices=[
        ('other', ''), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('fashion', 'Fashion')
        ], default='other')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    watchers = models.ManyToManyField(User, related_name="watchlist", blank=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.title}"


class Bid(models.Model):
    bidValue = models.PositiveIntegerField()
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    bidObject = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.bidder} bids {self.bidValue} on {self.bidObject}"


class Comment(models.Model):
    body = models.TextField(max_length=256, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    object = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} comments on {self.object}"

auctions/forms.py
from django import forms
from .models import Listing, Bid, Comment


class NewListing(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'basePrice', 'imageURL', 'category']

        widgets = {
            'description': forms.Textarea(attrs={'rows': '3', "cols": "40"}),
        }

class EmptyForm(forms.Form):
    pass


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['bidValue']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

        widgets = {
            'body': forms.Textarea(attrs={'rows': 3, 'cols': 40, 'placeholder': 'Your comment here...'})
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import User, Listing
from .forms import NewListing, EmptyForm, BidForm, CommentForm


def index(request):
    listings = Listing.objects.filter(active=True).order_by("timestamp").reverse()
    category = request.GET.get('category')
    if category:
        listings = listings.filter(category=category)

    return render(request, "auctions/index.html", {
        'title': 'home',
        'heading': 'Active listings',
        "listings": listings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        next = "index"
        if request.POST["next"]:
            next = request.POST["next"]

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect(next)
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required
def create(request):
    listing = NewListing()
    if request.method == 'POST':
        listing = NewListing(request.POST)
        if listing.is_valid():
            listing = listing.save(commit=False)
            listing.creator = request.user
            listing.save()
            return HttpResponseRedirect(reverse('listing', args=[listing.id]))
    return render(request, 'auctions/new.html', {
        "form": listing
    })


def listing(request, id):
    listing = Listing.objects.filter(id=id).first()
    if listing:
        lastBid = listing.bids.last()
        bidForm = BidForm()
        commentForm = CommentForm()

        comments = listing.comments.all()

        if lastBid:
            bidForm.fields['bidValue'].widget.attrs["min"] = lastBid.bidValue + 1
            bidForm.fields['bidValue'].widget.attrs["value"] = lastBid.bidValue + 1
        else:
            bidForm.fields['bidValue'].widget.attrs["min"] = listing.basePrice + 1
            bidForm.fields['bidValue'].widget.attrs["value"] = listing.basePrice + 1

        return render(request, 'auctions/listing.html', {
            "listing": listing,
            "bidForm": bidForm,
            'commentForm': commentForm,
            'comments': comments,
        })
    else:
        return render(request, "auctions/error.html", {
            "message": "Error 404: Requested listing not found."
        })


@login_required
def addToList(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = EmptyForm(request.POST)
        if form.is_valid():
            if listing and listing.active and listing not in request.user.watchlist.all():
                request.user.watchlist.add(listing)
                request.user.save()

    return HttpResponseRedirect(reverse('listing', args=[listing.id]))


@login_required
def removeFromList(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = EmptyForm(request.POST)
        if form.is_valid():
            if listing and listing in request.user.watchlist.all():
                request.user.watchlist.remove(listing)
                request.user.save()

    return HttpResponseRedirect(reverse('listing', args=[listing.id]))


@login_required
def placeBid(request, id):
    listing = Listing.objects.get(id=id)
    message = "Bid placed succesfully!"
    
    if request.method == 'POST':
        if listing and listing.active:
            form = BidForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.bidObject = listing
                form.bidder = request.user
                lastBid = listing.bids.last()
                
                if lastBid:
                    if form.bidValue>lastBid.bidValue:
                        form.save()
                    else:
                        message = "Bid not placed. Bid value must be greater than the last bid value - "+str(lastBid.bidValue)+"."
                else:
                    if form.bidValue>listing.basePrice:
                        form.save()
                    else:
                        message = "Bid not placed. Bid value must be greater than the base price - "+str(listing.basePrice)+"."
    print(message)
    return HttpResponseRedirect(reverse('listing', args=[listing.id]))


@login_required
def close(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == "POST" and listing and listing.active and listing.creator == request.user:
        form = EmptyForm(request.POST)
        if form.is_valid():
            listing.active = False

            if listing.bids.count() > 0:
                listing.winner = listing.bids.last().bidder
            listing.save()

    return HttpResponseRedirect(reverse('listing', args=[listing.id]))


@login_required
def comment(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST' and listing and listing.active:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.object = listing
            comment.save()

    return HttpResponseRedirect(reverse('listing', args=[listing.id]))


@login_required
def watchlist(request):
    listings = request.user.watchlist.order_by("timestamp").reverse()
    category = request.GET.get('category')

    if category:
        listings = listings.filter(category=category)

    return render(request, 'auctions/index.html', {
        'title': 'watchlist',
        'heading': 'My watchlist',
        'listings': listings.all()
    })


@login_required
def myListings(request, username):
    if username == request.user.username:
        user = User.objects.get(username=username)
        listings = Listing.objects.filter(creator=user).order_by("timestamp").reverse()

        category = request.GET.get('category')

        if category:
            listings = listings.filter(category=category)

        return render(request, 'auctions/index.html', {
            'title': 'my listings',
            'heading': 'My Listings',
            'listings': listings.all()
        })

auctions/templates/auctions/_listingCard.html
{% load static %}
{% load humanize %}

<div class="col mb-4" style="width:200px;">
<div class="card h-100">
    <div class="card-header">
        {{listing.title}}<br>
        <small> created {{ listing.timestamp|naturaltime }}</small>
    </div>

    {% if listing.imageURL %}
        <img src="{{ listing.imageURL }}" width="200px" height="200px" class="card-img-top" alt="...">
    {% else %}
        <img src="{% static 'auctions/index.png' %}" width="200px" height="200px" class="card-img-top">
    {% endif %}
    <div class="card-body" style="border-top:1px solid #343a40;">
        <p class="card-text">{{ listing.description }}</p>
        <div>
            <b>Base price:</b> INR {{ listing.basePrice }}
        </div>
        <div>
            {% if listing.bids.count %}
                {% with bid=listing.bids.last %}
                    <b>Last bid:</b> INR {{ bid.bidValue }} <small class="text-muted">{{ bid.timestamp|naturalday }}</small>
                {% endwith %}
            {% else %}
                No bids placed yet!
            {% endif %}
        </div>
    </div>
    <a class="card-footer" href="{% url 'listing' listing.id %}">View details</a>
</div>
</div>

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1 style="color: #a51c30;"> {{ message }} </h1>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div style="margin-bottom:16px">
        <form action="" style="float:right;">
            <div class="select" tabindex="1">
                {% if request.GET.category %}
                    <input class="selectopt" name="category" type="radio" id="default" checked>
                    <label for="default" class="option">{{ request.GET.category|capfirst }}</label>
                    <input class="selectopt" name="category" type="radio" id="opt" value="" onclick="submit()">
                    <label for="opt" class="option">All</label>
                {% else %}
                    <input class="selectopt" name="category" type="radio" id="opt1" value="" onclick="submit()" checked>
                    <label for="opt1" class="option">All</label>
                {% endif %}
                <input class="selectopt" name="category" type="radio" id="opt2" value="electronics" onclick="submit()">
                <label for="opt2" class="option">Electronics</label>
                <input class="selectopt" name="category" type="radio" id="opt3" value="furniture" onclick="submit()">
                <label for="opt3" class="option">Furniture</label>
                <input class="selectopt" name="category" type="radio" id="opt4" value="vehicle" onclick="submit()">
                <label for="opt4" class="option">Vehicle</label>
                <input class="selectopt" name="category" type="radio" id="opt5" value="fashion" onclick="submit()">
                <label for="opt5" class="option">Fashion</label>
                <input class="selectopt" name="category" type="radio" id="opt6" value="other" onclick="submit()">
                <label for="opt6" class="option">Other</label>
            </div>
        </form>
        <h2>{{ heading }}</h2>
    </div>

    <div class="row row-cols-1 row-cols-md-4 justify-content-center">
        {% for listing in listings %}
            {% include 'auctions/_listingCard.html' %}
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Auctions - {% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'auctions/styles.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'index' %}">Auctions</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Active listings</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'new' %}">Create listing</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="navbar-nav nav-item dropdown" style="float:right;">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg-right bg-dark" aria-labelledby="navbarDropdownMenuLink">
                            <a class="di" href="{% url 'myListings' request.user.username %}">My listings</a>
                            <a class="di" href="{% url 'watchlist' %}">Watchlist</a>
                            <div class="dropdown-divider"></div>
                            <a class="di" href="{% url 'logout' %}">Log out</a>
                        </div>
                    {% else %}
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container">
            {% block body %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% load humanize %}
{% load static %}

{% block title %}
 {{ listing.title }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row" style="margin-bottom: 24px;">
            <div class="col-10">
                <h1>{{ listing.title }}
                    {% if listing.active %}
                        <span class="badge badge-success">Active</span>
                    {% else %}
                        <span class="badge badge-danger">Inactive</span>
                    {% endif %}
                </h1>
                <small>listed by <span class="badge badge-success">{{ listing.creator }}</span> {{ listing.timestamp|naturaltime }}</small>
            </div>
            <div class="col-2" style="float:right; display:flex; align-items:center;">
                {% if request.user.is_authenticated %}
                    {% if listing.active %}
                        {% if listing.creator.username != request.user.username %}
                            {% if request.user not in listing.watchers.all %}
                                <form action="{% url 'addToList' listing.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="button" onclick="submit()" class="btn btn-success">Add to watchlist</button>
                                </form>
                            {% else %}
                                <form action="{% url 'removeFromList' listing.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="button" onclick="submit()" class="btn btn-danger btn-sm">Remove from watchlist</button>
                                </form>
                            {% endif %}
                        {% else %}
                            <form action="{% url 'close' listing.id %}" method="post">
                                {% csrf_token %}
                                <button type="button" onclick="submit()" class="btn btn-danger">Close bid</button>
                            </form>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {% if listing.imageURL %}
                    <img src="{{ listing.imageURL }}" width="250px" height="250px" alt="...">
                {% else %}
                    <img src="{% static 'auctions/index.png' %}" width="250px" height="250px">
                {% endif %}

                <p style="margin-top:16px; margin-bottom:16px;">{{ listing.description }}</p>

                <p>
                    <b>Base price:</b> INR {{ listing.basePrice }}
                </p>

                {% if listing.bids.count %}
                    {% with bid=listing.bids.last %}
                        <p>
                            <b>Last bid value:</b> INR {{ bid.bidValue }} <small>{{ bid.timestamp|naturaltime }}</small>
                        </p>
                    {% endwith %}
                {% else %}
                    <p>No bids placed yet!</p>
                {% endif %}

                {% if request.user.is_authenticated %}
                    {% if listing.active %}
                        {% if listing.creator.username != request.user.username %}
                            <form action="{% url 'placeBid' listing.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    {{ bidForm.bidValue }}
                                    <label for="id_bidValue" class="col-form-label">&nbsp</label>
                                    <input type="submit" class="btn btn-success" value="Place bid!">
                                </div>
                            </form>
                        {% endif %}
                    {% else %}
                        {% if request.user == listing.winner %}
                            <p class="alert alert-success" role="alert">
                                You have won the bid!
                            </p>
                        {% elif request.user == listing.creator %}
                            <p>You have closed the bid. {% if listing.winner %}<span class="badge badge-success">{{listing.winner.username}}</span> won the bid!</p>{% endif %}
                        {% else %}
                            <p class="alert alert-danger" role="alert">
                                The bid is inactive!
                            </p>
                        {% endif %}
                    {% endif %}
                {% else %}
                    Login to bid!
                {% endif %}
            </div>
            <div class="col-md-6">
                <h3>Comments</h3>
                <div id="comment" style="height:40vh; overflow-y:auto; box-shadow: 0 0 4px white; padding:8px; margin-bottom:16px; margin-top:16px;">
                {% if comments.count %}
                    {% for comment in comments %}
                        <hr>
                        <b>{{ comment.author.username }}</b> <small>said {{ comment.timestamp|naturaltime }}</small>
                        <p>{{ comment.body }}</p>
                    {% endfor %}
                {% else %}
                    <div style="display:flex; justify-content:center;">
                        <span>No comments to show!</span>
                    </div>
                {% endif %}
                </div>

                {% if listing.active and request.user.is_authenticated %}
                    <div>
                        <form action="{% url 'comment' listing.id %}" method="post">
                            {% csrf_token %}
                            {{ commentForm.body }}
                            <p>
                                <input type="submit" value="Submit">
                            </p>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        objDiv = document.getElementById("comment");
        objDiv.scrollTop = objDiv.scrollHeight;
    </script>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}
 login
{% endblock %}
{% block body %}
    <h2>Login</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}

{% block title %}
    New lisitng
{% endblock %}

{% block body %}
    <h1>New listing!</h1>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_title" class="col-sm-3 col-form-label">Title</label>
            <div class="col-sm-6">
                {{ form.title }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_description" class="col-sm-3 col-form-label">Description</label>
            <div class="col-sm-6">
                {{ form.description }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_basePrice" class="col-sm-3 col-form-label">Base Price <small>(INR)</small></label>
            <div class="col-sm-6">
                {{ form.basePrice }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_imgURL" class="col-sm-3 col-form-label">URL of the image <small>(optional)</small></label>
            <div class="col-sm-6">
                {{ form.imageURL }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_category" class="col-sm-3 col-form-label">Category <small>(optional)</small></label>
            <div class="col-sm-6">
                {{ form.category }}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <input type="submit" value="Add">
            </div>
        </div>
    </form>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %}
 login
{% endblock %}
{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}